### ISSUE TITLE
自校外服务器登录失败

### ISSUE THREAD

**Issue by CyberBarbarian** [Hyiker/bupt-gym-reserve#17]
服务器是校外自购的腾讯云，系统是ubuntu 20.04，在该学期接入统一认证后，校外的服务器便无法访问
请问除部署在校内服务器外，有无其他解决方案？
下面是Traceback
```
root@VM-8-14-ubuntu:~/bupt-gym-reserve# python3 main.py -u 我的学号 -p 我的密码
********** 2021-09-16 13:51:00 **********
正在摇D100... _(:з」∠)_
怎么又要干活o(￣ヘ￣o＃)
不存在session, 登录中...
Traceback (most recent call last):
  File "/root/bupt-gym-reserve/bupt_gym_reserve/http/session.py", line 43, in _recover_or_create_session
    with open(self.cookie_path) as foo:
FileNotFoundError: [Errno 2] No such file or directory: './cookie.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f115187b4f0>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gym.byr.moe', port=443): Max retries exceeded with url: /index.php (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f115187b4f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 47, in <module>
    session = GymSession(config=config)
  File "/root/bupt-gym-reserve/bupt_gym_reserve/http/session.py", line 22, in __init__
    self._recover_or_create_session()
  File "/root/bupt-gym-reserve/bupt_gym_reserve/http/session.py", line 58, in _recover_or_create_session
    self.login(self.config['username'], self.config['password'])
  File "/root/bupt-gym-reserve/bupt_gym_reserve/http/session.py", line 62, in login
    login_session = self.get(req_config['urls']['index'], headers=req_config['headers'])
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gym.byr.moe', port=443): Max retries exceeded with url: /index.php (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f115187b4f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))


```

**Comment by Az0s** [comment]
初步怀疑是https://gym.byr.moe 更新了规则导致在校外来自某些客户端的流量被服务器主动过滤  有时间了再看看

**Comment by Hyiker** [comment]
初步确定是因为健身房接入校园统一认证，统一认证网站不对校外开发导致的，解决方案是接入webvpn接口或者在校内部署服务器。

**Comment by Hyiker** [comment]
更新:
可以使用openconnect在校外服务器上连接北邮vpn后运行预约脚本，openconnect使用参考链接：
https://blog.csdn.net/m0_37991005/article/details/113514929
